sudo: required
services:
  - docker

before_install:
  - docker build -t hwrdy/docker-react-sample -f Dockerfile.dev .

script:
  - docker run hwrdy/docker-react-sample npm run test -- --coverage
# docker run -e CI=true USERNAME/docker-react npm run test